version: 2
updates:
  # For Python dependencies in the backend (using pip)
  - package-ecosystem: "pip"
    directory: "/SPM/backend" # Directory where requirements.txt is located
    schedule:
      interval: "daily"

  # For JavaScript dependencies in the frontend (using npm)
  - package-ecosystem: "npm"
    directory: "/SPM/frontend" # Directory where package.json and package-lock.json are located
    schedule:
      interval: "daily"
