name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
#   push:
#     branches: ["main", "justinlzx/cd"]

jobs:
  builds:
    runs-on: self-hosted

    steps:
      - name: Pull Docker images
        run: docker compose pull

      - name: Deploy to production
        run: docker compose -f docker-compose.yaml up -d
