name: Backend CI

on:
  #   workflow_dispatch:  # This can be triggered manually, or you can uncomment the 'push' or 'pull_request' if needed!
  # #   push:
  # #     branches:
  # #       - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend

    - name: Ensure backend .env exists
      run: |
        echo "Creating backend .env file..."
        cat > backend/.env << EOF
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
        SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
        TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}
        ENV=${{ vars.ENV }}
        FRONTEND_URL=${{ vars.FRONTEND_URL }}
        SMTP_PORT=${{ vars.SMTP_PORT }}
        SMTP_SERVER=${{ vars.SMTP_SERVER }}
        EOF

    - name: Install pre-commit
      run: pip install pre-commit
      working-directory: backend

    - name: Run pre-commit hooks
      run: pre-commit run --all-files
      working-directory: .

    - name: Run tests with coverage
      run: |
        pip install pytest pytest-cov  # Ensure pytest-cov is installed
        pytest --cov=backend/src --cov-report=term-missing --cov-report=html src/tests
      working-directory: backend
