name: Backend CI

on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
      working-directory: backend

    - name: Run tests
      run: |
        # Assuming you use pytest for testing
        pip install pytest
        pytest backend
      working-directory: backend

    - name: Check code formatting
      run: |
        # Assuming you use black for code formatting
        pip install black
        black --check backend
      working-directory: backend

    - name: Lint code
      run: |
        # Assuming you use flake8 for linting
        pip install flake8
        flake8 backend
      working-directory: backend
