name: Backend CI

on:
#   workflow_dispatch:  # This can be triggered manually, or you can uncomment the 'push' or 'pull_request' if needed.
# #   push:
# #     branches:
# #       - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend

    - name: Install pre-commit
      run: pip install pre-commit
      working-directory: backend

    - name: Run pre-commit hooks
      run: pre-commit run --all-files
      working-directory: .

    - name: Run tests with coverage
      run: |
        pip install pytest pytest-cov  # Ensure pytest-cov is installed
        pytest --cov=backend/src --cov-report=term-missing --cov-report=html backend/src/tests
        python -m coverage report  # To show coverage report in the logs
      working-directory: backend

    - name: Check code formatting
      run: |
        # Assuming you use black for code formatting
        pip install black
        black --check backend
      working-directory: backend

    - name: Lint code
      run: |
        # Assuming you use flake8 for linting
        pip install flake8
        flake8 backend
      working-directory: backend
