name: Docker Image CI

on:
  push:
    branches: ["main", "justinlzx/cd"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    environment: production
    runs-on: linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker compose -f docker-compose.yaml build
          docker compose -f docker-compose.yaml push
