name: Docker Image CI

on:
  push:
    branches: ["main", "justinlzx/cd"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker images
        run: docker compose build
      - name: Push to Docker Hub
        run: docker compose push
