name: Docker Image CI

on:
  push:
    branches: ["main", "justinlzx/cd"]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        run: |
          docker compose -f docker-compose.yaml build
          docker compose -f docker-compose.yaml push
