name: Docker Image CI

on:
  push:
    branches: ["main", "justinlzx/cd"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: linux/arm64

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker images
        run: docker compose build
      - name: Push to Docker Hub
        run: docker compose push
