name: CI pipeline

on:
  push:
    branches: ["main", "justinlzx/cd"]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Ensure .env exists
        run: |
          if [ ! -f "frontend/.env" ]; then
            echo "Creating .env file..."
            touch frontend/.env
            echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> frontend/.env
            # Add other environment variables as needed
          fi

      - name: Build and push
        run: |
          docker compose -f docker-compose.yaml build
          docker compose -f docker-compose.yaml push
